version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install tox
      - run: cd ./clean_py && tox

  pypi_publish_mock:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            pip install twine
            twine upload --repository testpypi dist/*
  pypi_publish_prod:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            pip install twine
            twine upload dist/*
workflows:
  # **all workflows currently running for every branch? filtering not working?
  tests_pypi_publish_mock:
    jobs:
      - test
      - pypi_publish_mock:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
  tests_pypi_publish_prod:
    jobs:
      - test
      - pypi_publish_prod:
          requires:
            - test
          filters:
            branches:
              only:
                - master
