version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - name: install tox
      - run: pip install tox
      - name: run tox
      - run: cd ./project && run tox

workflows:
  version: 1.0.0
  test:
    jobs:
      - test