version: 2.1

jobs:
  test:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install tox
      # - run: cd ./project && run tox