version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install tox
      - run: cd ./clean_py && tox

  pypi_publish_test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            pip install twine
            twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            pip install twine
            twine upload dist/*
workflows:
  # **all workflows currently running for every branch? filtering not working?
  # **consider limiting twine uploads to master (redundnat test upload)
  test_pypi_publish_test:
    jobs:
      - test
      - pypi_publish_test:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
  test_pypi_publish:
    jobs:
      - test
      - pypi_publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
