version: 2.1

jobs:
  test:
    working_directory: ~/clean_py
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install tox
      - run: cd ./clean_py && tox
workflows:
  test_and_build:
    jobs:
      - test
